---
version: 2.1
jobs:
  Unit-Test:
    docker:
      - image: python:3.8.16-bullseye
    steps:
      - run:
          name: Install git
          command: |
            apt-get install git
      - checkout
      - run:
          name: Download & verify the packer binary
          command: |
            wget https://releases.hashicorp.com/packer/1.8.6/packer_1.8.6_linux_amd64.zip
            wget https://releases.hashicorp.com/packer/1.8.6/packer_1.8.6_SHA256SUMS
            sha256sum -c packer_1.8.6_SHA256SUMS --ignore-missing
            unzip packer_1.8.6_linux_amd64.zip
            mv packer /usr/bin/packer
      - run:
          name: Install requirements
          command: |
            python -m pip install -r ./requirements/dev.txt
            pre-commit install
      - run:
          name: Run Unit Tests
          command: |
            set +o pipefail
            pre-commit try-repo . packer-fmt --verbose --all-files | tee ./tests/result
            set -eo pipefail
            grep -q -F "files were modified by this hook" ./tests/result
            grep -q -F "tests/bad.pkr.hcl" ./tests/result
            grep -q -v -F "tests/ok.pkr.hcl" ./tests/result
workflows:
  unit_test:
    jobs:
      - Unit-Test
